### ISSUE TITLE
Create an API

### ISSUE THREAD

**Issue by waldoj** [openva/vabusinesses.org#20]
At a minimum, it should be able to:

* [x] return JSON for a given corporation ID
* [x] search against business names

**Comment by ttavenner** [comment]
The API is now 99% working and is ready to go live somewhere. The only thing I don't currently have working is searching with geo data. I just need to dig through your geo search issue to understand how the data is organized so I can put together the search and add the necessary fields into the model. But every other piece of data is searchable and they can all be combined together. Relationships between indexes have also been built into the model and act as subqueries, so each result returned from a business search will have arrays with results for amendments, mergers, and officers if found. There is also auto-generated HTML documentation at '/docs'.

**Comment by waldoj** [comment]
:us: :+1: :fireworks: Wonderful news! I will try this out this evening and see what I can manage with it. An API on top of this data will let people do all kinds of magnificent things with this data, I do not doubt.

(Five minutes later.)

OK, I'm most of the way there. So far, this is really easy. :) I've got an EC2 firewall issue (I can't get into port 3000), and for some reason `api.js` is ignoring the `host` specification in `config.json`, but after I get my kid to bed in, like 3 hours because Jesus God I just can't even, I'll take another crack at this!

**Comment by ttavenner** [comment]
Strange, I just tested it locally to make sure I hadn't hard coded something somewhere. It seems to update just fine, but that is entirely internal. It's possible that other issues exist when trying to proxy from external. Let me know if there are any errors I can help with. I don't use EC2 often but I spend a lot of time doing Linux network config for web servers. If nothing else you can try hard coding the port directly in `api.js` on line four. Just replace `config.port` with the port number you want, but its also possible the traffic isn't reaching the node server for some other reason.

**Comment by ttavenner** [comment]
Commented elsewhere, but for posterity the host issue was on my end. I hadn't actually set the host in `api.js`, which is obviously a problem. I fix has been pushed.

**Comment by waldoj** [comment]
Is there any documentation of the methods supported? I'm just fishing around in the dark right now. :)

**Comment by waldoj** [comment]
(Please pardon the terribly mixed metaphor!)

**Comment by ttavenner** [comment]
If you go to the root `/` it will return all of the routes in JSON. If you visit `/docs` you can see an HTML documentation of the routes. It's not perfect yet but it gives you a complete list of the fields available for each route along with their data type. I can create more specific documentation if desired or work on getting the auto-generated documentation to be more detailed. I'm thinking something similar to what I put together in the README for the [Open Health Inspection API] (https://github.com/Code4HR/open-health-inspection-api)

**Comment by waldoj** [comment]
I've got it running!

https://api.vabusinesses.org/

Sample business record:

http://api.vabusinesses.org/businesses?id=0047626

Now I can start building the site on top of this API (e.g., browse functionality, individual records display, etc). I note that one can string together parameters—like name and address—which is perfect for naive searches, e.g., "the Johnson Company in Lexington" becomes `?name=Johnson&city=Lexington`. That's the one feature that I think is _really_ going to make this useful to all kinds of people for all kinds of reasons.

This is just brilliant, @ttavenner. I can't thank you and Code for Hampton Roads enough for this, and I think a lot of other folks will feel the same!
