### ISSUE TITLE
Errors when adding some Elasticsearch maps

### ISSUE THREAD

**Issue by waldoj** [openva/vabusinesses.org#24]
2:

``` json
{"error":"MapperParsingException[No handler for type [int] declared on field [total_shares]]","status":400}
```

3:

``` json
{"error":"MapperParsingException[No type specified for property [coordinates]]","status":400}
```

4:

``` json
{"error":"MapperParsingException[No handler for type [int] declared on field [shares_auth]]","status":400}
```

9: 

``` json
{"error":"MapperParsingException[No type specified for property [coordinates]]","status":400}
```

**Comment by ingenuity2k** [comment]
Just for people running into `No handler for type [int] declared on field` in the future: `int` has to be `integer`, since `int` is not a valid data type in elasticsearch. (This page is the only result google comes up with)

**Comment by waldoj** [comment]
Ha! Having often suffered from the exactly-one-result-and-it-doesn't-help problem, I salute your service to future googlers.
