### ISSUE TITLE
Add functionality to search by municipality

### ISSUE THREAD

**Issue by waldoj** [openva/vabusinesses.org#25]
People should be able to narrow their search by municipality.

* [x] get a list of all municipalities (just cities and counties right now) in Virginia
* [x] obtain GeoJSON for every one of those municipalities
* [x] [pre-index all of those shapes](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-filter.html#_pre_indexed_shape)
* [x] document somewhere how to re-index those shapes
* [x] add an Elasticsearch interface to search using that GeoJSON
* [x] add all Virginia towns, too

**Comment by waldoj** [comment]
One month later, a solution! @missinglink kindly provided [a solution on the Elasticsearch mailing list](https://groups.google.com/forum/#!msg/elasticsearch/OZ3oMSUnp_k/y1fm8__km50J). I haven't had time to make a thorough comparison, but [Peter's working example](https://gist.github.com/missinglink/d5d37082303bfdb5529c) shows that I was being too clever by half in storing the coordinates of each business. I was using a mapping like such:

```json
"location": {
	"type": "object", 
	"properties": {
		"coordinates": {
			"type": "geo_point", 
			"lat_lon": "true"
		}
	}
}
```

when all I really needed was:

```json
"location": {
    "type": "geo_shape"
}
```

So, that's awkward. Then, in an embarrassing oversight, I failed to put any geodata in [the debug code that I put on a Gist](https://gist.github.com/waldoj/004f77755179d862fe3a), but it looks like I've been encoding that data properly:

```
"location": {
    "type": "point",
    "coordinates": "38.4241518711,-78.8895320659"
}
```

A change to the table map might be all that's required to get things working. I hope to have the time to try that out within a day or two.

**Comment by waldoj** [comment]
Phew. That did it. I just barely got it working at this moment, but it's working—lookups against pre-indexed shapes are returning valid-looking results.

**Comment by waldoj** [comment]
I've got the `geosearch.php` functionality ported to `search.php`, and it mostly works. The catch is that it only works when running a search with no terms (e.g., `q=coffee`). A search with terms produces nothing. I think this is a consequence of how we build queries.

**Comment by waldoj** [comment]
Huh, now some place names are just returning an (uncaught) exception when we execute `$client->search($params);` It makes everything halt in its tracks, dying unceremoniously. (It's clearly a bug in php-elasticsearch.) Probably best to figure out what the actual problem is. My guess is that some places aren't actually listed in our locations index, and that error isn't handled properly.

**Comment by ttavenner** [comment]
Sorry that I am late to the party in noticing this. How did you imagine business search working under this system. I had built into the API the ability to search for a business within a certain distance of a given point, which worked for the geo_point format but not for a geo_shape. Is the idea that the municipality shape would be in this field or is it some other shape?

**Comment by waldoj** [comment]
Yeah, it turned out that I needed to use `geo_shape`—Elasticsearch doesn't support using `geo_point` for a point (oddly) that you're trying to locate within an indexed shape. Now municipalities' shapes are all indexed in a `shapes` table, allowing filters like such, to limit query results to businesses within a given municipality:

```json
"filter": {
	"geo_shape": {
		"location": {
			"indexed_shape": {
				"id": "061",
				"type": "municipalities",
				"index": "shapes",
				"path": "geometry"
			}
		}
	}
}
```

The `id` field uses the GNIS ID for each locality. Every city and county is included, and I intend to also index all towns.

**Comment by waldoj** [comment]
All that remains is get GeoJSON for all Virginia towns. I've had no luck finding that so far.

**Comment by waldoj** [comment]
I've uploaded all towns data, as `towns.geojson`. It just remains to turn it into Elasticsearch's bulk import format. And consider simplifying the polygons?

**Comment by waldoj** [comment]
Bedford's reversion to a town has left them without a GNIS ID. They had a city ID, but it's no longer applicable. So they're not going to be included.

**Comment by waldoj** [comment]
Phew, OK. All done. I'm going to close this ticket, and open a new one for Bedford.
